import type { Restaurant, Food, Category, Coupon } from "@/types/domain.types";

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Spice Garden",
    slug: "spice-garden",
    description: "Authentic Bengali & Indian cuisine since 2015.",
    cuisineTags: ["Bengali", "Indian", "Biryani"],
    avgRating: 4.6,
    totalReview: 312,
    minOrderAmount: 200,
    deliveryFee: 40,
    avgPrepTimeMin: 25,
    isOpen: true,
    address: { city: "Dhaka", area: "Gulshan" },
  },
  {
    id: "r2",
    name: "Burger Barn",
    slug: "burger-barn",
    description: "Smash burgers, crispy fries, thick shakes.",
    cuisineTags: ["American", "Fast Food", "Burgers"],
    avgRating: 4.3,
    totalReview: 198,
    minOrderAmount: 150,
    deliveryFee: 30,
    avgPrepTimeMin: 15,
    isOpen: true,
    address: { city: "Dhaka", area: "Banani" },
  },
  {
    id: "r3",
    name: "Sushi Theory",
    slug: "sushi-theory",
    description: "Premium omakase-style sushi, delivered.",
    cuisineTags: ["Japanese", "Sushi", "Asian"],
    avgRating: 4.8,
    totalReview: 87,
    minOrderAmount: 500,
    deliveryFee: 0,
    avgPrepTimeMin: 30,
    isOpen: true,
    address: { city: "Dhaka", area: "Gulshan" },
  },
  {
    id: "r4",
    name: "Pizza Peak",
    slug: "pizza-peak",
    description: "Wood-fired pizzas with fresh, local toppings.",
    cuisineTags: ["Italian", "Pizza"],
    avgRating: 4.4,
    totalReview: 256,
    minOrderAmount: 300,
    deliveryFee: 50,
    avgPrepTimeMin: 20,
    isOpen: false,
    address: { city: "Dhaka", area: "Dhanmondi" },
  },
  {
    id: "r5",
    name: "Taco Loco",
    slug: "taco-loco",
    description: "Street-style tacos, burritos, and quesadillas.",
    cuisineTags: ["Mexican", "Street Food"],
    avgRating: 4.2,
    totalReview: 143,
    minOrderAmount: 180,
    deliveryFee: 35,
    avgPrepTimeMin: 18,
    isOpen: true,
    address: { city: "Dhaka", area: "Uttara" },
  },
  {
    id: "r6",
    name: "Green Bowl",
    slug: "green-bowl",
    description: "Healthy bowls, salads, and smoothies.",
    cuisineTags: ["Healthy", "Salads", "Vegan"],
    avgRating: 4.5,
    totalReview: 89,
    minOrderAmount: 250,
    deliveryFee: 40,
    avgPrepTimeMin: 12,
    isOpen: true,
    address: { city: "Dhaka", area: "Gulshan" },
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: "c1", name: "Biryani & Rice", image: "", order: 1, restaurantId: "r1" },
  { id: "c2", name: "Curries", image: "", order: 2, restaurantId: "r1" },
  { id: "c3", name: "Bread & Roti", image: "", order: 3, restaurantId: "r1" },
  { id: "c4", name: "Desserts", image: "", order: 4, restaurantId: "r1" },
];

export const MOCK_FOODS: Food[] = [
  {
    id: "f1",
    name: "Chicken Biryani",
    description:
      "Fragrant basmati rice cooked with tender chicken, saffron and whole spices.",
    images: [],
    price: 280,
    discountPrice: 250,
    isAvailable: true,
    isVegetarian: false,
    spiceLevel: 2,
    variants: [
      {
        name: "Size",
        options: [
          { label: "Regular", extraPrice: 0 },
          { label: "Large", extraPrice: 80 },
        ],
      },
      {
        name: "Add-on",
        options: [
          { label: "Extra Egg", extraPrice: 20 },
          { label: "Raita", extraPrice: 15 },
        ],
      },
    ],
    avgRating: 4.7,
    totalReview: 124,
    totalSold: 890,
    restaurantId: "r1",
    categoryId: "c1",
    restaurantName: "Spice Garden",
  },
  {
    id: "f2",
    name: "Mutton Kacchi",
    description: "Slow-cooked mutton layered with aromatic rice — a celebration classic.",
    images: [],
    price: 420,
    isAvailable: true,
    isVegetarian: false,
    spiceLevel: 3,
    variants: [],
    avgRating: 4.9,
    totalReview: 76,
    totalSold: 430,
    restaurantId: "r1",
    categoryId: "c1",
    restaurantName: "Spice Garden",
  },
  {
    id: "f3",
    name: "Paneer Butter Masala",
    description: "Cottage cheese cubes in a rich, buttery tomato gravy.",
    images: [],
    price: 320,
    isAvailable: true,
    isVegetarian: true,
    spiceLevel: 1,
    variants: [
      {
        name: "Bread with",
        options: [
          { label: "Naan", extraPrice: 30 },
          { label: "Roti", extraPrice: 15 },
        ],
      },
    ],
    avgRating: 4.5,
    totalReview: 51,
    totalSold: 234,
    restaurantId: "r1",
    categoryId: "c2",
    restaurantName: "Spice Garden",
  },
  {
    id: "f4",
    name: "Classic Smash Burger",
    description: "Double smashed beef patty, American cheese, pickles, special sauce.",
    images: [],
    price: 350,
    discountPrice: 299,
    isAvailable: true,
    isVegetarian: false,
    spiceLevel: 0,
    variants: [
      {
        name: "Size",
        options: [
          { label: "Single", extraPrice: 0 },
          { label: "Double", extraPrice: 120 },
        ],
      },
    ],
    avgRating: 4.4,
    totalReview: 92,
    totalSold: 654,
    restaurantId: "r2",
    categoryId: "c1",
    restaurantName: "Burger Barn",
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: "cp1",
    code: "WELCOME50",
    type: "PERCENTAGE",
    value: 50,
    maxDiscount: 150,
    minOrderAmount: 300,
    validTill: "2026-12-31",
  },
  {
    id: "cp2",
    code: "FREEDEL",
    type: "FREE_DELIVERY",
    value: 0,
    minOrderAmount: 200,
    validTill: "2026-09-30",
    restaurantName: "Spice Garden",
  },
  {
    id: "cp3",
    code: "FLAT100",
    type: "FLAT",
    value: 100,
    minOrderAmount: 400,
    validTill: "2026-07-31",
  },
];

export const CUISINE_CATEGORIES = [
  { label: "Biryani", emoji: "🍛" },
  { label: "Burgers", emoji: "🍔" },
  { label: "Pizza", emoji: "🍕" },
  { label: "Sushi", emoji: "🍣" },
  { label: "Healthy", emoji: "🥗" },
  { label: "Mexican", emoji: "🌮" },
  { label: "Desserts", emoji: "🍰" },
  { label: "Bengali", emoji: "🍲" },
];
